# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        pass_filenames: false
        entry: poetry run black .
        language: system
        types: [python]

      - id: pytest
        name: pytest
        pass_filenames: false
        entry: poetry run pytest
        language: system
        stages: [push]
        types: [python]
        verbose: true

      - id: mypy
        name: mypy
        pass_filenames: false
        entry: poetry run mypy --package todo_project_name --package tests
        language: system
        stages: [push]
        types: [python]
        verbose: true
