name: Check typing

on: [push, pull_request]

jobs:
  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -m pip install poetry
      - run: poetry run python3 -m mypy .
